version: '3.5'

services:
  mysql:
    image: mysql:8.0.11
    container_name: mysql
    env_file: ./docker/mysql/.env
    ports:
      - "3333:3306"
    volumes:
      - ./docker/mysql/var/log:/var/log:delegated
      - ./docker/mysql/etc/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-vue-ddd-with-cqrs

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6666:6379"
    command: redis-server --appendonly yes
    networks:
      - laravel-vue-ddd-with-cqrs

  npm:
    image: node:10-alpine
    container_name: npm
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    environment:
      - NODE_ENV=development
    command: yarn
    networks:
      - laravel-vue-ddd-with-cqrs

  composer:
    build: ./docker/composer
    container_name: composer
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    command: install --optimize-autoloader
    networks:
      - laravel-vue-ddd-with-cqrs

  php:
    build: ./docker/php
    container_name: php
    depends_on:
      - mysql
      - redis
      - composer
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
      - ./docker/php/var/log:/var/log/laravel:delegated
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    command: >
      ash -c
        "./docker/php/wait_for_composer_container_exit.sh \
        && sudo chmod -R 777 storage/ bootstrap/cache \
        && sudo php artisan config:cache \
        && sudo php artisan cache:clear \
        && sudo php artisan route:clear \
        && sudo php artisan view:clear \
        && sudo php artisan clear-compiled \
        && sudo php artisan migrate:fresh \
        && /usr/local/sbin/php-fpm -F"
    networks:
      - laravel-vue-ddd-with-cqrs

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/var/log:/var/log/nginx:delegated
    depends_on:
      - php
    networks:
      - laravel-vue-ddd-with-cqrs

networks:
  laravel-vue-ddd-with-cqrs:
    name: laravel-vue-ddd-with-cqrs
