version: '3.5'

services:
  mysql:
    image: mysql:8.0.11
    container_name: mysql
    env_file: ./docker/mysql/.env
    ports:
      - "3333:3306"
    volumes:
      - ./docker/mysql/var/log:/var/log:delegated
      - ./docker/mysql/etc/my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6666:6379"
    command: redis-server --appendonly yes

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
      - ./docker/php/var/log:/var/log/laravel
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    depends_on:
      - mysql
      - redis
    command: >
      bash -c
        "sudo chmod -R 777 storage/ bootstrap/cache \
        && composer install --optimize-autoloader \
        && sudo php artisan config:cache \
        && sudo php artisan cache:clear \
        && sudo php artisan route:clear \
        && sudo php artisan view:clear \
        && sudo php artisan clear-compiled \
        && sudo php artisan migrate:fresh \
        && /usr/local/sbin/php-fpm -F"

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/var/log:/var/log/nginx
    depends_on:
      - php
