version: '3.5'

services:
  mysql:
    image: mysql:8.0.11
    container_name: mysql
    env_file: ./docker/mysql/.env
    ports:
      - "3333:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./storage/logs/mysql/:/var/log/:delegated
    networks:
      - laravel-vue-ddd-with-cqrs

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6666:6379"
    command: redis-server --appendonly yes
    networks:
      - laravel-vue-ddd-with-cqrs

  composer:
    build: ./docker/composer
    container_name: composer
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    command: install --optimize-autoloader
    networks:
      - laravel-vue-ddd-with-cqrs

  app:
    build: ./docker/app
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - composer
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
      - ./storage/logs/laravel/:/var/log/laravel/:delegated
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    command: >
      ash -c
        "rc-service php-fpm start \
        && ./docker/app/wait-for.composer-container-exit.sh \
        && ./laravel.generate-key.sh \
        && chmod -R 777 storage/ bootstrap/cache \
        && php artisan clear-compiled \
        && php artisan cache:clear \
        && php artisan route:clear \
        && php artisan config:cache \
        && php artisan view:cache \
        && php artisan migrate:fresh \
        && yarn \
        && yarn dev \
        && yarn hot"
    tty: true
    networks:
      - laravel-vue-ddd-with-cqrs

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx/:/var/log/nginx/:delegated
    depends_on:
      - app
    networks:
      - laravel-vue-ddd-with-cqrs

networks:
  laravel-vue-ddd-with-cqrs:
    name: laravel-vue-ddd-with-cqrs
