version: '3.5'

services:
  mysql:
    image: mysql:8.0.11
    container_name: lvdc_mysql
    env_file: ./docker/mysql/.env
    ports:
      - "3333:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./storage/logs/mysql/:/var/log/:delegated
    networks:
      - laravel-vue-ddd-with-cqrs

  redis:
    image: redis:latest
    container_name: lvdc_redis
    restart: always
    ports:
      - "6666:6379"
    command: redis-server --appendonly yes
    networks:
      - laravel-vue-ddd-with-cqrs

  node:
    build: ./docker/node
    image: lvdc/node:latest
    container_name: lvdc_node
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
    command: >
      ash -c
        "yarn && yarn dev"
      tty: true
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    networks:
      - laravel-vue-ddd-with-cqrs

  composer:
    build: ./docker/composer
    container_name: lvdc_composer
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    command: install --optimize-autoloader
    networks:
      - laravel-vue-ddd-with-cqrs

  app:
    build: ./docker/app
    container_name: lvdc_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - composer
      - node
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
      - ./storage/logs/laravel/:/var/log/laravel/:delegated
    working_dir: /var/www/laravel-vue-ddd-with-cqrs
    command: >
      ash -c
        "rc-service php-fpm start \
        && chmod -R 777 storage/ bootstrap/cache \
        && ./docker/app/wait-for-container-exit.sh composer \
        && ./laravel.generate-key.sh \
        && php artisan optimize:clear \
        && php artisan config:cache \
        && php artisan view:cache \
        && php artisan migrate:fresh \
        && ./docker/app/wait-for-container-exit.sh node \
        && yarn hot"
    tty: true
    networks:
      - laravel-vue-ddd-with-cqrs

  nginx:
    image: nginx
    container_name: lvdc_nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/laravel-vue-ddd-with-cqrs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx/:/var/log/nginx/:delegated
    depends_on:
      - app
    networks:
      - laravel-vue-ddd-with-cqrs

networks:
  laravel-vue-ddd-with-cqrs:
    name: laravel-vue-ddd-with-cqrs
